dbName : '~/.fileEm/s2article.db'
# Set the tables
# Main table of journal article
Journal_articles:
  tableName: 'Journal_articles'
  # Set the elements in the table
  paperId:
    elementName: 'paperId'
    elementType: 'str'
    columnName:  'VARCHAR'
    otherKW:     'PRIMARY KEY'
  title:
    elementName: 'title'
    elementType: 'str'
    columnName:  'VARCHAR'
    otherKW:     'NOT NULL'
  fields:
    elementName: 'fields'
    elementType: 'str'
    columnName:  'VARCHAR'
  pubyear:
    elementName: 'pubyear'
    elementType: 'int'
    columnName:  'INT'
  pages:
    elementName: 'pages'
    elementType: 'str'
    columnName:  'VARCHAR'
  vol:
    elementName: 'vol'
    elementType: 'int'
    columnName:  'INT'
  journal:
    elementName: 'journal'
    elementType: 'str'
    columnName:  'VARCHAR'
    foreignKey:
      table: Journal
      name:  Id
  authors:
    elementName: 'authors'
    elementType: 'str'
    columnName:  'VARCHAR'
  abstract:
    elementName: 'abstract'
    elementType: 'str'
    columnName:  'TEXT'
  doi:
    elementName: 'doi'
    elementType: 'str'
    columnName:  'VARCHAR'
  path:
    elementName: 'path'
    elementType: 'str'
    columnName:  'VARCHAR'
  nref:
    elementName: 'nref'
    elementType: 'int'
    columnName:  'INT'
Author:
  tableName: 'Author'
  authorId:
    elementName: 'authorId'
    elementType: 'int'
    columnName:  'INT'
    otherKW:     'PRIMARY KEY'
  Name:
    elementName: 'Name'
    elementType: 'str'
    columnName:  'VARCHAR'
    otherKW:     'NOT NULL'
Journal:
  tableName: 'Journal'
  Id:
    elementName: 'Id'
    elementType: 'str'
    columnName:  'VARCHAR'
    otherKW:     'PRIMARY KEY'
  Name:
    elementName: 'Name'
    elementType: 'str'
    columnName:  'VARCHAR'
  Alternative:
    elementName: 'Alternative'
    elementType: 'str'
    columnName:  'VARCHAR'
